// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR9Zk4-1aEivy4Ih4noEDosThIRsJa_7Q',
    appId: '1:446136742143:web:832998ce9be5845caf9cca',
    messagingSenderId: '446136742143',
    projectId: 'sip-and-sip',
    authDomain: 'sip-and-sip.firebaseapp.com',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    measurementId: 'G-JQ3XR8GF4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtT-jIjXP-HB5nZmW6AGhzhbCvk2Mo4cU',
    appId: '1:446136742143:android:a9df2897a6469ec5af9cca',
    messagingSenderId: '446136742143',
    projectId: 'sip-and-sip',
    storageBucket: 'sip-and-sip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-i6czTJJP48dLG5g3-Uh2QXC1ALgKM8w',
    appId: '1:446136742143:ios:9b841629adce0089af9cca',
    messagingSenderId: '446136742143',
    projectId: 'sip-and-sip',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    iosBundleId: 'com.example.sipAndSip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-i6czTJJP48dLG5g3-Uh2QXC1ALgKM8w',
    appId: '1:446136742143:ios:9b841629adce0089af9cca',
    messagingSenderId: '446136742143',
    projectId: 'sip-and-sip',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    iosBundleId: 'com.example.sipAndSip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR9Zk4-1aEivy4Ih4noEDosThIRsJa_7Q',
    appId: '1:446136742143:web:57191d4750ed9abbaf9cca',
    messagingSenderId: '446136742143',
    projectId: 'sip-and-sip',
    authDomain: 'sip-and-sip.firebaseapp.com',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    measurementId: 'G-EW14ZZ9K3P',
  );

}