// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIza... (Your Web Key)',
    appId: '1:XXXXXXXXXXXX:web:XXXXXXXXXXXX',
    messagingSenderId: 'XXXXXXXXXXXX',
    projectId: 'sip-and-sip',
    authDomain: 'sip-and-sip.firebaseapp.com',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIza... (Your Android Key)',
    appId: '1:XXXXXXXXXXXX:android:XXXXXXXXXXXX',
    messagingSenderId: 'XXXXXXXXXXXX',
    projectId: 'sip-and-sip',
    storageBucket: 'sip-and-sip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza... (Your iOS Key)',
    appId: '1:XXXXXXXXXXXX:ios:XXXXXXXXXXXX',
    messagingSenderId: 'XXXXXXXXXXXX',
    projectId: 'sip-and-sip',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    iosBundleId: 'com.example.sipAndSip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIza... (Your MacOS Key)',
    appId: '1:XXXXXXXXXXXX:ios:XXXXXXXXXXXX',
    messagingSenderId: 'XXXXXXXXXXXX',
    projectId: 'sip-and-sip',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    iosBundleId: 'com.example.sipAndSip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIza... (Your Windows Key)',
    appId: '1:XXXXXXXXXXXX:web:XXXXXXXXXXXX',
    messagingSenderId: 'XXXXXXXXXXXX',
    projectId: 'sip-and-sip',
    authDomain: 'sip-and-sip.firebaseapp.com',
    storageBucket: 'sip-and-sip.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
